name: a_vida_de_mariguelinho
description: Apenas um simples aplicativo que fiz para aprender Flutter e homenagear um amiguinho.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  speech_to_text: ^5.5.0
  avatar_glow: ^2.0.2
  highlight_text: ^1.4.0
  assets_audio_player: ^3.0.4+3
  youtube_player_iframe: ^2.3.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
    image_path: 'assets/images/mariguelinho_main_picture.jpg'
    android: "launcher_icon"
    ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/mangrove.jpg
      - assets/images/mariguelinho_main_picture.jpg
      - assets/images/mariguelinho1.jpg
      - assets/images/marighelinho2.jpg
      - assets/images/marighelinho3.jpg
      - assets/images/marighelinho4.jpg
      - assets/images/marighelinho5.jpg
      - assets/images/marighelinho6.jpg
      - assets/images/marighelinho7.jpg
      - assets/images/marighelinho8.jpg
      - assets/images/marighelinho9.jpg
      - assets/images/marighelinho10.jpg
      - assets/images/marighelinho11.jpg
      - assets/images/marighelinho12.jpg
      - assets/images/marighelinho13.jpg
      - assets/images/marighelinho14.jpg
      - assets/images/marighelinho15.jpg
      - assets/images/marighelinho15.jpg
      - assets/images/marighelinho16.jpg
      - assets/images/marighelinho17.jpg
      - assets/images/marighelinho18.jpg
      - assets/images/marighelinho19.jpg
      - assets/images/marighelinho20.jpg
      - assets/images/marighelinho21.jpg
      - assets/images/marighelinho22.jpg
      - assets/images/marighelinho23.jpg
      - assets/images/marighelinho24.jpg
      - assets/images/marighelinho25.jpg
      - assets/images/marighelinho26.jpg
      - assets/images/marighelinho27.jpg
      - assets/images/marighelinho28.jpg
      - assets/images/marighelinho29.jpg
      - assets/images/marighelinho30.jpg
      - assets/images/marighelinho31.jpg
      - assets/images/marighelinho32.jpg
      - assets/images/marighelinho33.jpg
      - assets/images/marighelinho34.jpg
      - assets/images/marighelinho35.jpg
      - assets/images/marighelinho36.jpg
      - assets/images/marighelinho37.jpg
      - assets/images/marighelinho38.jpg
      - assets/images/marighelinho39.jpg
      - assets/images/marighelinho40.jpg
      - assets/images/marighelinho41.jpg
      - assets/images/marighelinho42.jpg
      - assets/images/marighelinho43.jpg
      - assets/images/marighelinho44.jpg
      - assets/images/marighelinho45.jpg
      - assets/images/marighelinho46.jpg
      - assets/images/marighelinho47.jpg
      - assets/images/marighelinho48.jpg
      - assets/images/marighelinho49.jpg
      - assets/images/marighelinho50.jpg
      - assets/images/marighelinho51.jpg
      - assets/images/marighelinho52.jpg
      - assets/images/marighelinho53.jpg
      - assets/images/crypto_home/dogecoin_logo.png
      - assets/images/crypto_home/shibainu_logo.png
      - assets/images/crypto_home/ethereum_logo.png
      - assets/images/crypto_home/bitcoin_logo.png
      - assets/images/crypto_home/usdcoin_logo.png
      - assets/images/crypto_home/cardano_logo.png
      - assets/images/crypto_home/pix_logo.png
      - assets/images/crypto_home/dogecoin_qrcode.png
      - assets/images/crypto_home/shibainu_qrcode.png
      - assets/images/crypto_home/ethereum_qrcode.png
      - assets/images/crypto_home/bitcoin_qrcode.png
      - assets/images/crypto_home/usdcoin_qrcode.png
      - assets/images/crypto_home/cardano_qrcode.png
      - assets/images/crypto_home/pix_qrcode.png
      - assets/images/sport_club_internacional/sportclubinternacional1.gif
      - assets/images/sport_club_internacional/sportclubinternacional2.jpg
      - assets/audio/beatheart.mp3
      - assets/audio/meow1.mp3
      - assets/audio/meow2.mp3
      - assets/audio/meow3.mp3
      - assets/audio/meow4.mp3
      - assets/audio/meow5.mp3
      - assets/audio/meow6.mp3
      - assets/audio/meow7.mp3
      - assets/audio/meow8.mp3
      - assets/audio/meow9.mp3
      - assets/audio/meow10.mp3
      - assets/audio/meow11.mp3
      - assets/audio/meow12.mp3
      - assets/audio/meow13.mp3
      - assets/audio/meow14.mp3
      - assets/audio/meow15.mp3
      - assets/audio/meow16.mp3
      - assets/audio/meow17.mp3
      - assets/audio/meow18.mp3
      - assets/audio/meow19.mp3
      - assets/audio/meow20.mp3
      - assets/audio/meow21.mp3
      - assets/audio/meow22.mp3
      - assets/audio/meow23.mp3
      - assets/audio/meow24.mp3
      - assets/audio/meow25.mp3
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific 'variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
